# This file has been generated by map-protocol.sh

# # Tags

# ## Common
DENY_ABORT = bytes([0xfe])
DENY_RETRY = bytes([0xfd])

# ## Client -> Server

# ### Misc

# Includes two parameters: a 1 byte length and a length bytes
# sized string.
# String (name) should use UTF-8 and not exceed 20 characters
SET_NAME = bytes([0x20])

# ### Queue
JOIN_QUEUE = bytes([0x01])
QUIT_QUEUE = bytes([0x02])
ACCEPT_GAME = bytes([0x03])

# ### Game
ASK_AGAIN = bytes([0x06])
ANSWER_A = bytes([0x10])
ANSWER_B = bytes([0x11])
ANSWER_C = bytes([0x12])
PASS = bytes([0x1f])
QUIT_GAME = bytes([0x1e])

# ## Server -> Client

# ### Queue
GAME_FOUND = bytes([0x81])

# Includes two parameters:
# An 8 bytes Match ID and a 1 byte player ID
# Player ID will be either 0x01 or 0x02,
# for player 1 or 2 respectively
JOINED_GAME = bytes([0x82])

# ### Game

# Includes one parameter:
# and a NULL terminated question description in UTF-8
ASK_TO_01 = bytes([0x83])
ASK_TO_02 = bytes([0x84])

PASS_TO_01 = bytes([0x85])
PASS_TO_02 = bytes([0x86])

# Includes one parameter, a 4 bytes little-endian player score
SCORE_01 = bytes([0x87])
SCORE_02 = bytes([0x88])

GAME_END = bytes([0x89])
GAME_ABORTED = bytes([0x8a])

# # Data

SET_NAME_MAX_SIZE = bytes([20])
