#!/usr/bin/env sh

# Maps server/protocol.h to client/protocol.py

sed_script='
1,3d                               # Delete "once" mechanism
4i # This file has been generated by map-protocol.sh
4i
$d                                 # Delete corresponding endif
s|//|#|                            # Fix comment syntax
s|#define ([^ ]+) ([^ ]+)|\1 = bytes([\2])| # Make Python variables
'

sed -E -e "$sed_script" server/protocol.h > client/protocol.py

# The above keeps a trailing new line at the end of the file which
# I'm not sure how to fix otherwise
sed -i -e '$d' client/protocol.py
